### ISSUE TITLE
Time synchronization with other sensors

### ISSUE THREAD

**Issue by AndyFrancesco29** [ros-event-camera/metavision_driver#42]
Hi,
I would like to ask how to use this ros driver to synchronize the time of the event camera and other sensors like LiDAR. For other sensors, we have used the Network Time Protocol (NTP) to synchronize their timestamp. However, it seems that the event camera does not follow this protocol and the timestamp is different. 

Is their any method to synchronize different sensors? Or is it possible that we can modify this driver and follow the network time? Thank you very much.

**Comment by berndpfrommer** [comment]
AFAIK there is no way to control the clock of the event camera. But you can:
- send an external sync pulse at well defined intervals, e.g. every second (pps), and then look at the ExternalTrigger events provided by the camera. That will allow you to associate the camera-provided event time with host time.
- provide external sync trigger pulses directly from the Lidar, if the Lidar supports that. Then you can associate the lidar event time with the camera event time

Please be aware though that the ROS message's header stamp also allows you to establish the offset between camera event time and host time. Please refer to the documentation [here](https://github.com/ros-event-camera/event_camera_codecs/?tab=readme-ov-file#event-time-stamps) and [here](https://github.com/ros-event-camera/event_camera_py/#about-timestamps).

**Comment by AndyFrancesco29** [comment]
Thanks for your reply.

We would like to synchronize the event camera, RGB camera, and LiDAR. According to my understanding, the NTP synchronizes the ROS system time, so that our LiDAR and camera can have the same timestamp. 

Right now, our camera seems to have a sync pulse but LiDAR does not. So if I generate the sync pulse from the event camera, can I find the offset between the event camera and the whole ROS time?

**Comment by berndpfrommer** [comment]
What event camera do you have? The most recent models cannot generate a sync pulse.
Will the sync pulse trigger the frame camera? Can the rgb cam generate a pulse?

**Comment by AndyFrancesco29** [comment]
I am using Prophesee EVK4. 

Or what if I use PPS, that is to generate the pulse from GPS and input it to the event camera and RGB camera?

**Comment by berndpfrommer** [comment]
I don't think EVK4 can do it. From the link you posted:
"This configuration can not be used with our EVK4 and EVK3 using Gen4.1, IMX636 and GenX320 sensors as those cameras do not provide a Trigger Out facility. For this sensor, there are two alternate options:"
Yes, trigger both event camera and frame camera from a common source. Then from the trigger events recorded by the event camera you will know when the shutter of your frame camera fell, in terms of event time.
How to get the Lidar synchronized I don't know. You may not be able to do that easily in hardware. But again, the event camera messages have a ROS time stamp in their header which should reasonably correspond to the header time stamps on the ros messages arriving from the Lidar. Is that not good enough?

**Comment by AndyFrancesco29** [comment]
We take the timestamp of the first LiDAR frame and the timestamp of the first event to calculate the offset between these two sensors but they do not actually refer to the same "time". It seems that they have 200 ms - 300 ms discrepancy, which means that Lidar first returns around two frames and then the event camera. I am not sure why this happens.

Sorry for so many questions, but I still have one question. Also if I use an external trigger to synchronize an RGB camera and an event camera, how do I know if two sensors are synchronized? Will the timestamp be the same, or will there be an event from the event camera that indicates an image is taken by the camera? If it is the second one, how do I know which image refers to this event if I have a lot of images?

**Comment by berndpfrommer** [comment]
Maybe it helps if you explained in detail what timestamps you are *exactly* referring to, what constitutes/triggers the "first" event and why you would expect these two time stamps to coincide. Please read up what external trigger events are for an event camera. Hook up an external trigger to your event camera and see what data you get. Run your camera at 1fps, then you can easily associate trigger events and frames, and see how much delay there is. Note that the metavision driver only gets data packets from the camera about every 10ms by default (can be changed, see docs), so if you run your camera at more than 100fps   you must expect multiple trigger events per ros message.

**Comment by AndyFrancesco29** [comment]
The timestamp in my sense refers to the "t" in [x, y, p, t] which can be obtained after decoding. So for the timestamp you mentioned, does it refer to the time when the aggregated events are sent? And I can modify "event_message_time_threshold" parameter to change that?

**Comment by berndpfrommer** [comment]
When you decode, the "t" you get is in sensor time, which starts near zero, and as such is arbitrarily shifted with respect to any other time stamp you get e.g. from your lidar. 

> We take the timestamp of the first LiDAR frame and the timestamp of the first event to calculate the offset between these two sensors but they do not actually refer to the same "time". It seems that they have 200 ms - 300 ms discrepancy, which means that Lidar first returns around two frames and then the event camera. I am not sure why this happens.

How can it then be only shifted by 200-300ms? It should be shifted by a huge amount.

**Comment by AndyFrancesco29** [comment]
The shifted 200-300ms is the one after adding the offset. For example, the first event has a "t" of 100, and the timestamp of the first LiDAR frame is 170, then the offset is 70. I add 70 to all the "t" in the event. But still, they have 200-300ms shift.

**Comment by berndpfrommer** [comment]
So you are directly comparing the lidar sensor time to the event camera time? I don't know anything about the Lidar sensor time, but I know for sure that the event camera time stamps cannot be compared directly with any other sensor's time (except when you have 2 event cameras connected with a sync cable).
You first have to figure out what the offset is of the event camera time with respect to host time. Pick any event message (skip the first few maybe to make sure the driver has fully started up). Now look at the header.stamp of the ROS message, and look at the sensor time of the first event in that message. That will give you the offset between your sensor time 't' and the host time.
Now you need to follow a similar procedure for your lidar. This will give you the offset between your lidar sensor time and host time. Now you can convert sensor times  to host time, and compare the two time stamps.
To verify that this is working you will need to identify when something moves in your lidar data, and the corresponding event in your event data. Shift the sensor times to host time, and you should be within a few ms.

**Comment by berndpfrommer** [comment]
Sorry, I misunderstood what you were saying. You are looking at the first packet arriving, using that as a reference. Do those two packets arrive at the same host time?

**Comment by AndyFrancesco29** [comment]
May I ask how to check the host time by using the tools [here](https://github.com/ros-event-camera/event_camera_py)?

**Comment by berndpfrommer** [comment]
Let's say you are playing data from a bag, the ROS messages have a header with a time stamp. So in [this example](https://github.com/ros-event-camera/event_camera_py?tab=readme-ov-file#decoding-event-array-messages)  put a print(msg) into the code (or better, print(msg.header)). That should give you a ROS timestamp in nanoseconds since epoch. That is the host time stamp when the first event in the message arrived at the host.

**Comment by AndyFrancesco29** [comment]
Thanks for your advice.
I have tried that and it seems that they are still not match.
Here is an accumulated event camera frame within time 1706682860.147466469 and 1706682860.247416646:
![6891_1710303807_hd](https://github.com/ros-event-camera/metavision_driver/assets/40028911/5c46232b-071d-482f-bcbd-0fe90a348827)
Two vehicles in the red box seems to be parallel.

And here is the Lidar frame with timestamp:
![6890_1710303783_hd](https://github.com/ros-event-camera/metavision_driver/assets/40028911/b1acb57f-1136-4864-a9a2-1132c6a9cea3)
This one is from the same timestamp of LiDAR, but they are not parallel. For the timestamp after 200ms, they seems to be same:
![6889_1710303757_hd](https://github.com/ros-event-camera/metavision_driver/assets/40028911/37b867c4-a079-413e-8c82-5a509783d78a)
This will have some problem when I calibrate the extrinsic parameters between these two sensors.

Maybe the message arrival time of the sensor is not consistent with the time they generate the raw data?

**Comment by berndpfrommer** [comment]
So the frame based camera is 42ms late. Your frame based camera has a latency of up to* 1/fps. So if you run e.g. 40Hz, your  will have 25ms/2 = 24ms latency. However, the accumulation for the event camera adds latency for that sensor.
So is your lidar data now delayed or ahead of the event camera?

**Comment by AndyFrancesco29** [comment]
I think the delay is not due to the frame rate. As you can see, the accumulation for the event camera and the RGB image has the same content, so I suppose the sensors are obtaining the information at the same time. Is that right? However, when ROS gets the information, RGB has delay compared to the events. If it is cause by the frame rate, they should generate different images. I am not sure if my understanding is correct.

Similarly, the LiDAR data are also delayed. And the delay is around 200ms.

**Comment by berndpfrommer** [comment]
You said:
> I find the RGB image and the event accumulated image that have the same clock number on the iPad screen, and see their time stamp. 
And now you say:
> I think the delay is not due to the frame rate. As you can see, the accumulation for the event camera and the RGB image has the same content, so I suppose the sensors are obtaining the information at the same time. Is that right? 
Of course if you look for the two frames that show the same content, then they will show the same content. That's because you searched along the time axis for both sensors. Not because they got the information at the same time.

**Comment by AndyFrancesco29** [comment]
I think there is some confusion here. By saying the same content, I mean two sensors obtain the same information at the same moment/time. In our scenario, the same content means the clock number on the iPad screen, so I mean the image should be taken at the same time.

By saying the time stamp, I mean the host time. However, they have different host time in ROS. If the content of the images is the same, shouldn't the host time stamp be same?

**Comment by berndpfrommer** [comment]
> By saying the time stamp, I mean the host time. However, they have different host time in ROS (here it is 1710319287.968997916 and 1710319287.926637218). If the content of the images is the same, shouldn't the host time stamp be same?
By no means. The same content means that in the physical world those two events happened at the same time. Then there are different processing delays until that content reaches the respective sensor. For the event camera those delays are shorter.
Take for instance the frame based camera. Let's say the number on the display *just* crossed over from 0 to 1 at t_host = 0, and at exactly that time, the shutter opened at the frame based camera. It will keep the shutter open for e.g. 10 msec, then close the shutter, send the image via USB to the host. The host will receive the image, look at its clock, which at that point already says t_host = 10ms + other_delay. So it will put a time stamp on of e.g. 12ms. This is the time stamp you will see on the ROS packet. The same probably happens with the lidar. It will likely complete a full rotation before it sends data to the host (I never worked with LIDAR, just guessing). Only then does the ros driver put on the host time stamp.

**Comment by AndyFrancesco29** [comment]
Thank you very much for your explanation. I will close this issue.
