### ISSUE TITLE
Issue when trying to open both RGB and Event cameras

### ISSUE THREAD

**Issue by samchopra2003** [ros-event-camera/metavision_driver#49]
For the RGB camera, I am using the Flir Blackfly S with this driver: https://github.com/ros-drivers/flir_camera_driver. I am using a Prophesee Evk4 event camera.

When I try to run both drivers I am unable to open the event camera which is launched second in my ros2 launch file. My rgb camera which is launched first is successfully launched.

I am getting the following error:
![image(39)](https://github.com/user-attachments/assets/60f4490f-2d39-4a2a-bf10-a330300482df)

`24071693` is the rgb camera serial number. When I run the event camera launch file I typically do not specify a serial number, and the event camera driver is able to detect the camera. 

System details

    operating system/version: Ubuntu 22.04.4 LTS (Jammy Jellyfish)
    ROS version: ROS 2 Humble

**Comment by samchopra2003** [comment]
The event camera launch file works fine when launched individually and not running it together with the rgb camera.

**Comment by samchopra2003** [comment]
Seems like I had used the same serial_number argument for both launch files resulting in a conflict.

**Comment by berndpfrommer** [comment]
Good. have been able to run exactly this combination in the past, so if it no longer worked it would imply a regression.
