### ISSUE TITLE
Is it possible to convert bags of prophesee_event_msgs/EventArray to event_camera_msgs?

### ISSUE THREAD

**Issue by Ericsii** [ros-event-camera/metavision_driver#52]
I have several rosbag datasets recorded using the official `prophesee_ros_wrapper`, and I want to migrate my code to `ros-event-camera` and still use the old data set for testing.

Is it possible to convert bags of `prophesee_event_msgs/EventArray` to `event_camera_msgs` or any way to read data using `event_camera_codecs`

**Comment by berndpfrommer** [comment]
That should be possible with the [``event_camera_tools``](https://github.com/ros-event-camera/event_camera_tools/?tab=readme-ov-file#ros1-only-tools) repo. The conversion tool works in ROS1 only so far, but once you have it in ROS1 format you can convert to ROS2.
At the moment many of the packages under ros-event-camera work for both ROS1 and ROS2, but all new ones are just ROS2.

**Comment by Ericsii** [comment]
Thanks for your answer. This project is awesome! And it would be better if there was a project site with some tutorials on using all these tools.
