### ISSUE TITLE
ROS2 metavision_driver vs metavision_viewer - unexpected behaviour

### ISSUE THREAD

**Issue by TheDarcLord** [ros-event-camera/metavision_driver#53]
Hello,

I'm working the Jetson-Orin-Nano. As such, just getting the SilkyCam Gen3.1 to work has been a fun little journey.

**What is interaction between `openeb`, and your ROS Metavision driver ?**

I've been trying to resolve it myself by building this particular package from src, but at this point I need your guidance.

To run the SilkyCam on the Jetson, CenturyArks provides modified build files for `openeb`, as their driver installer doesn't seem to be compatible.

Upon the installation of the modified `openeb`, the SilkyCam works as expected when calling `metavision_viewer` or `metavision_platform_info`.

However, after running `source /opt/ros/humble/setup.bash` the camera is inaccessible reporting;
`ros2 run metavision_driver driver_node` ==> `Error 102002: Camera is not yet initialized.`
`metavision_platform_info` ==> `No systems USB connected have been found on your platform.`

CenturyArks has a form to fill out in order to access the src files for modifying `openeb`.
I'll include it here: https://centuryarks.com/en/download-form/
It includes a ReadMe stating which files need to be replaced.

Thank you for producing this package for ROS!

**Comment by berndpfrommer** [comment]
The latest versions of the ROS2 driver rely on the ROS2 openeb_vendor package, which is essentially a packaged release of openeb for the ROS2 world. You can use the "ldd" command on the ROS2 metavision driver .so files to find their dependencies. The output of the ldd command should show that the ROS2 driver is using openeb files located somewhere under /opt/ros/humble/
Thank you for pointing me to the CenturyArks form. I did not know they had made that available. I'll have a look at it. It's probably the source code for their camera plugin. Great to see that we may be able to build this for the Jetson family.

**Comment by TheDarcLord** [comment]
Thanks for the hint @berndpfrommer!

It was simply a matter of merging and replacing 
`openeb/build/lib` to the `ros/humble/opt/openeb_vendor/lib` ...

For those that follow!
1. Follow the build steps for `openeb`, after replacing the files specified by CenturyArk
2. Merge/Replace the `/opt/ros/humble/opt/openeb_vendor/lib` directory with the `openeb/build/lib` directory
3. Last quirk ~ when running the `event_camera_renderer`, the camera name/topic defaults to "/metavision_driver" ... Be sure to use rostopic to double check the name the `metavision_driver` node has provided.

Cheers!

**Comment by berndpfrommer** [comment]
I patched the openeb_vendor package to now include the SilkyEvCam plugin.

**Comment by berndpfrommer** [comment]
But for the life of it I cannot find where the event_camera_renderer is subscribing to metavision_driver. The search string "metavision" does not even appear in the event_camera_renderer package (and it shouldn't, since you can also use it with e.g. the DVS cameras).
The metavision_driver itself also appears to be only publishing under "event_camera", not "metavision_driver". Some more pointers are appreciated.

**Comment by TheDarcLord** [comment]
Good morning @berndpfrommer,

It might be a quirk in the way I’ve mashed these packages together.
To clarify, after my fix:
1. Running the `metavision_driver driver_node` (on the Jetson) successfully starts publishing events on the topic `metavision_driver/events`
2. On my Ubuntu (22.04) Tower, the same node (without modification) publishes the events on the `event_camera/events` topic
3. Upon parsing `camera:=metavision_driver` on the Jetson or `camera:=event_camera` on the Tower to the `event_camera_renderer`, everything works as expected.

As to where the camera name `metavision_driver` was coming from, I was stumped as well.
Could not find it in any of the source files.

**Comment by berndpfrommer** [comment]
If you are running this as a bare rosnode (not through a launch file), then it makes sense, because the driver node name will default to metavision_driver
