### ISSUE TITLE
Support lastest metavisionSDK

### ISSUE THREAD

**Issue by Ericsii** [ros-event-camera/metavision_driver#54]
Prophesee has released [openeb v5.0.0](https://github.com/prophesee-ai/openeb/releases/tag/5.0.0), which leads to some broken changes and introducing new features. Could you support the latest version?

**Comment by berndpfrommer** [comment]
Could you please [try this branch](https://github.com/ros-event-camera/metavision_driver/tree/add_mv5_compatibility)?

**Comment by Ericsii** [comment]
I've tested on Ubuntu24.04 ROS-jazzy, and it works fine. Thanks for your work :)
